Repository steve1316/granblue-automation-pyautogui, pull requests merged in 2023-04, with the labels that each got.

#170 Patch a bot like click behaviour
  src-tauri/backend/utils/mouse_utils.py
Labels: bug

#171 Add a new game mode
  .gitignore
  src-tauri/backend/bot/combat_mode_v2.py
  src-tauri/backend/bot/game.py
  src-tauri/backend/bot/game_modes/generic_v2.py
  src-tauri/backend/bot/window.py
  src-tauri/backend/unit_test/test_mouse.py
  src-tauri/backend/unit_test/test_parser.py
  src-tauri/backend/unit_test/test_window.py
  src-tauri/backend/unit_test/tools.py
  src-tauri/backend/utils/image_utils.py
  src-tauri/backend/utils/mouse_utils.py
  src-tauri/backend/utils/parser.py
  src-tauri/headless.bat
  src-tauri/headless.py
  src-tauri/scripts/campaign_exclusive_mw_v2.txt
  src-tauri/scripts/campaign_exclusive_v2.txt
  src-tauri/scripts/six_dragon_raid_v2.txt
  src-tauri/scripts/template_v2.txt
Labels: documentation, enhancement

#172 Feature/sandbox update
  src-tauri/backend/bot/game.py
  src-tauri/backend/bot/game_modes/arcarum_sandbox.py
  src-tauri/backend/utils/settings.py
  src-tauri/images/buttons/arcarum_sandbox_defender.jpg
  src-tauri/images/buttons/arcarum_sandbox_herald.jpg
  src-tauri/images/buttons/arcarum_sandbox_zone_mundus.jpg
  src/context/BotStateContext.tsx
  src/data/data.json
  src/pages/Settings/FarmingModesHelpers/ArcarumSandboxHelper.tsx
  src/pages/Settings/index.tsx
Labels: bug, enhancement

#178 Constrain the Group Number when Farming Mode is Arcarum Sandbox
  src/pages/Settings/index.tsx
Labels: enhancement

#177 Merge Xeno Clash into Special Farming Mode
  README.md
  src-tauri/backend/bot/combat_mode.py
  src-tauri/backend/bot/game.py
  src-tauri/backend/bot/game_modes/special.py
  src-tauri/backend/bot/game_modes/xeno_clash.py
  src-tauri/backend/utils/image_utils.py
  src-tauri/backend/utils/settings.py
  src-tauri/backend/utils/twitter_room_finder.py
  src-tauri/headless.py
  src-tauri/images/buttons/special_showdown.jpg
  src-tauri/images/buttons/special_showdowns_xeno_clashes.jpg
  src-tauri/images/buttons/special_xeno_clash.jpg
  src/context/BotStateContext.tsx
  src/data/data.json
  src/helpers/FarmingModeHelpers/XenoClashHelper.tsx
  src/pages/ExtraSettings/index.tsx
  src/pages/Settings/index.tsx
Labels: enhancement

#179 Have the Support Summon picker be inline and not in a separate Modal
  src/components/CustomSelect/index.tsx
  src/components/CustomTransferList/index.tsx
  src/pages/ExtraSettings/index.tsx
  src/pages/Settings/index.tsx
Labels: enhancement

#176 docs: update readme
  README.md
Labels: documentation

#181 Fix dark mode not being on by default
  src/App.tsx
Labels: bug

#189 Fix navigation bug for Guild Wars Day 1
  src-tauri/backend/bot/game_modes/guild_wars.py
Labels: bug

#190 Fix alignment for confidence level input components
  src/pages/ExtraSettings/index.tsx
Labels: enhancement

#187 Improve handling of mouse speed
  src-tauri/backend/utils/image_utils.py
  src-tauri/backend/utils/mouse_utils.py
  src-tauri/backend/utils/settings.py
  src/context/BotStateContext.tsx
  src/pages/ExtraSettings/index.tsx
Labels: enhancement

#185 fix bugs for and add features for generic V2
  src-tauri/backend/bot/combat_mode_v2.py
  src-tauri/backend/bot/game.py
  src-tauri/backend/bot/game_modes/generic_v2.py
  src-tauri/backend/bot/window.py
  src-tauri/backend/utils/debugger.py
  src-tauri/backend/utils/image_utils.py
  src-tauri/backend/utils/mouse_utils.py
  src-tauri/backend/utils/parser.py
  src-tauri/images/buttons/calibration_left.jpg
  src-tauri/images/buttons/calibration_right.jpg
  src-tauri/images/buttons/heal_disabled.jpg
  src-tauri/images/headers/auto_enabled_header.jpg
  src-tauri/images/headers/auto_ready_header.jpg
Labels: bug, enhancement

#194 Fix list index for Guild Wars NM100
  src-tauri/backend/bot/game_modes/guild_wars.py
Labels: bug
